"""Configuration primitives for POLARIS."""

from .adaptive_thresholds import (
    CATEGORY_THRESHOLDS,
    DEFAULT_THRESHOLD,
    EXPANDED_GARDEN_QUERIES,
    HIGH_CONFIDENCE_QUERIES,
    LOW_CONFIDENCE_QUERIES,
    MEDIUM_CONFIDENCE_QUERIES,
    RECOMMENDED_GARDEN_QUERIES,
    STRUCTURAL_QUERIES,
    ULTRA_FAST_QUERIES,
    UNRELIABLE_QUERIES,
    VEGETATION_QUERIES,
    get_threshold,
)

__all__ = [
    "CATEGORY_THRESHOLDS",
    "DEFAULT_THRESHOLD",
    "EXPANDED_GARDEN_QUERIES",
    "HIGH_CONFIDENCE_QUERIES",
    "LOW_CONFIDENCE_QUERIES",
    "MEDIUM_CONFIDENCE_QUERIES",
    "RECOMMENDED_GARDEN_QUERIES",
    "STRUCTURAL_QUERIES",
    "ULTRA_FAST_QUERIES",
    "UNRELIABLE_QUERIES",
    "VEGETATION_QUERIES",
    "get_threshold",
]
